# Generated by Django 3.0.7 on 2020-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='name',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
