# Generated by Django 3.0.7 on 2020-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0002_auto_20200616_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitExcelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('planedYear', models.DateField()),
                ('quarter1', models.IntegerField(blank=True, null=True)),
                ('quarter2', models.IntegerField(blank=True, null=True)),
                ('quarter3', models.IntegerField(blank=True, null=True)),
                ('quarter4', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('fbnumber', models.IntegerField(blank=True, null=True)),
                ('onepager', models.IntegerField(blank=True, null=True)),
                ('coctyp', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('projectname', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('editortip', models.CharField(blank=True, max_length=500, null=True)),
                ('editorextern', models.CharField(blank=True, max_length=500, null=True)),
                ('budgetpmb', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.CharField(blank=True, max_length=500, null=True)),
                ('projectnumber', models.IntegerField(blank=True, null=True)),
                ('typ', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
