# Generated by Django 3.0.7 on 2020-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0003_splitexceldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='status',
            new_name='Status',
        ),
    ]
