# Generated by Django 3.0.7 on 2020-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0004_auto_20200619_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitexceldata',
            name='Status',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
