# Generated by Django 3.0.7 on 2020-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0005_auto_20200619_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitexceldata',
            name='Status',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
