# Generated by Django 3.0.7 on 2020-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0006_auto_20200619_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitexceldata',
            name='planedYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
