# Generated by Django 3.0.7 on 2020-06-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0007_auto_20200619_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='fbnumber',
            new_name='Q1',
        ),
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='quarter1',
            new_name='Q2',
        ),
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='quarter2',
            new_name='Q3',
        ),
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='quarter3',
            new_name='Q4',
        ),
        migrations.RenameField(
            model_name='splitexceldata',
            old_name='quarter4',
            new_name='fbnr',
        ),
        migrations.AddField(
            model_name='splitexceldata',
            name='contractperson',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='splitexceldata',
            name='pmpl',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='budget',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='budgetpmb',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='coctyp',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='department',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='editorextern',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='editortip',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='projectname',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='typ',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
