# Generated by Django 3.0.7 on 2020-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0009_auto_20200619_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitexceldata',
            name='budget',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='budgetpmb',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='coctyp',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='department',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='editorextern',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='editortip',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='projectname',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='splitexceldata',
            name='typ',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
