# Generated by Django 3.0.7 on 2020-06-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelmanagementApp', '0010_auto_20200619_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitExcelData',
        ),
    ]
